CREATE TABLE "ai-super-agent-yupi-nextjs_chat" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text DEFAULT 'Untitiled Chat' NOT NULL,
	"visibility" varchar DEFAULT 'private' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ai-super-agent-yupi-nextjs_embedding" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"resourceId" uuid,
	"content" text NOT NULL,
	"embedding" vector(1536) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-super-agent-yupi-nextjs_message" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"chatId" uuid NOT NULL,
	"role" varchar NOT NULL,
	"content" text NOT NULL,
	"parts" json NOT NULL,
	"attachments" json,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-super-agent-yupi-nextjs_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-super-agent-yupi-nextjs_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ai-super-agent-yupi-nextjs_resource" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "ai-super-agent-yupi-nextjs_embedding" ADD CONSTRAINT "ai-super-agent-yupi-nextjs_embedding_resourceId_ai-super-agent-yupi-nextjs_resource_id_fk" FOREIGN KEY ("resourceId") REFERENCES "public"."ai-super-agent-yupi-nextjs_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-super-agent-yupi-nextjs_embedding" ADD CONSTRAINT "embedding_resource_id_fk" FOREIGN KEY ("resourceId") REFERENCES "public"."ai-super-agent-yupi-nextjs_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-super-agent-yupi-nextjs_message" ADD CONSTRAINT "message_chat_id_fk" FOREIGN KEY ("chatId") REFERENCES "public"."ai-super-agent-yupi-nextjs_chat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chat_created_at_idx" ON "ai-super-agent-yupi-nextjs_chat" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "embedding_idx" ON "ai-super-agent-yupi-nextjs_embedding" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "message_created_at_idx" ON "ai-super-agent-yupi-nextjs_message" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "post_name_idx" ON "ai-super-agent-yupi-nextjs_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "resource_created_at_idx" ON "ai-super-agent-yupi-nextjs_resource" USING btree ("createdAt");